name: Deploy GC Function

# TODO: this _must_ be changed
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    
    steps:
      - id: deploy
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: talkspace-public-api
          runtime: python37
          credentials: ${{ secrets.GCP_SA_KEY }}

      # Example of using the output
      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
