steps:
- id: deploy
  uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
  with:
    name: talkspace-public-api
    runtime: python37
    credentials: ${{ secrets.GCP_SA_KEY }}

# Example of using the output
- id: test
  run: curl "${{ steps.deploy.outputs.url }}"
