name: Deploy to production

on:
  push:
    branches:
      - main

env:
  GC_PROJECT: ${{ secrets.GC_PROJECT }}
  GC_KEY: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: "290.0.1"
        project_id: ${{ secrets.GC_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy
      uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
      with:
        name: talkspace-public-api
        runtime: python37
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        source_dir: src
        entry_point: refresh_data

