name: Deploy GC Function

# TODO: this _must_ be changed
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    
    steps:
    - id: Lint
      run: flake8 src/
